In [1]:
import tensorflow as tf
from tensorflow.contrib import rnn
import matplotlib.pyplot as plt
import numpy as np

/Users/admin/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
timesteps = seq_length = 3
data_dim = 4 #data variable
hidden_dim = 4
output_dim = 1
learning_rate = 0.05
iterations = 100
n_inputs = 50

In [3]:
x = np.array([[[1., 2., 3., 4., 5.],
              [1., 2., 3., 4., 5.],
              [1., 2., 3., 4., 5.],
              [1., 2., 3., 4., 5.],
             ]])
print(x)

x = np.reshape(x,[1, 5, 4]) # data reshape
print(x)
y = np.array([[1., 2., 3., 4., 5.]])

[[[1. 2. 3. 4. 5.]
  [1. 2. 3. 4. 5.]
  [1. 2. 3. 4. 5.]
  [1. 2. 3. 4. 5.]]]
[[[1. 2. 3. 4.]
  [5. 1. 2. 3.]
  [4. 5. 1. 2.]
  [3. 4. 5. 1.]
  [2. 3. 4. 5.]]]


In [4]:
trainX = x[:4]
trainY = y[:4]
testX = x[4:]
testY = y[4:]

In [5]:
dataX = []
dataY = []

In [6]:
# LSTM

In [7]:
X = tf.placeholder(tf.float32, [None, 5, data_dim]) # 5 -> data length
Y = tf.placeholder(tf.float32, [None, 5]) # 5 -> data length

In [8]:
def lstm_cell():
    cell = rnn.BasicLSTMCell(hidden_dim, state_is_tuple = True)
    return cell

In [9]:
cell = rnn.BasicLSTMCell(num_units = hidden_dim, state_is_tuple = True)
multi_cells = rnn.MultiRNNCell([lstm_cell() for _ in range(5)], state_is_tuple=True)

In [10]:
outputs, _states = tf.nn.dynamic_rnn(multi_cells, X, dtype = tf.float32)

In [11]:
Y_pred = tf.contrib.layers.fully_connected(outputs[:, -1], output_dim, activation_fn = None)

In [12]:
loss = tf.reduce_sum(tf.square(Y_pred - Y))
train = tf.train.RMSPropOptimizer(learning_rate).minimize(loss)

In [13]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [14]:
for i in range(iterations):
    _, cost = sess.run([train, loss], feed_dict={X: trainX, Y:trainY})
    print("[step: {}] loss: {}".format(i+1, cost))

[step: 1] loss: 55.00187683105469
[step: 2] loss: 43.83588409423828
[step: 3] loss: 33.457496643066406
[step: 4] loss: 21.829246520996094
[step: 5] loss: 13.607568740844727
[step: 6] loss: 10.613224029541016
[step: 7] loss: 10.056053161621094
[step: 8] loss: 10.00294303894043
[step: 9] loss: 10.000090599060059
[step: 10] loss: 10.000001907348633
[step: 11] loss: 10.0
[step: 12] loss: 10.0
[step: 13] loss: 10.0
[step: 14] loss: 10.0
[step: 15] loss: 10.0
[step: 16] loss: 10.0
[step: 17] loss: 10.0
[step: 18] loss: 10.0
[step: 19] loss: 10.0
[step: 20] loss: 10.0
[step: 21] loss: 10.0
[step: 22] loss: 10.0
[step: 23] loss: 10.0
[step: 24] loss: 10.0
[step: 25] loss: 10.0
[step: 26] loss: 10.0
[step: 27] loss: 10.0
[step: 28] loss: 10.0
[step: 29] loss: 10.0
[step: 30] loss: 10.0
[step: 31] loss: 10.0
[step: 32] loss: 10.0
[step: 33] loss: 10.0
[step: 34] loss: 10.0
[step: 35] loss: 10.0
[step: 36] loss: 10.0
[step: 37] loss: 10.000000953674316
[step: 38] loss: 10.000007629394531
[step: 3