# Pytorch Tutorials 따라치기

- 참고 : [Pytorch 60분만에 끝장내기](https://tutorials.pytorch.kr/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)
<br>
<br>
- Pytorch?
1. <span style="color:red">Numpy</span>를 대체하면서 GPU를 이용한 연산이 필요한 경우 사용
2. 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

## Tensors

In [2]:
from __future__ import print_function
import torch

### 초기화되지 않은 5*3 행렬 생성

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 3.6893e+19, 0.0000e+00],
        [3.6893e+19, 1.2612e-44, 1.5975e-43],
        [1.3873e-43, 1.4153e-43, 4.4842e-44],
        [1.6255e-43, 1.4153e-43, 1.5274e-43],
        [1.5695e-43, 1.5554e-43, 1.5975e-43]])


### 무작위로 초기화된 행렬 생성

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4670, 0.0797, 0.1038],
        [0.3203, 0.9177, 0.0489],
        [0.5730, 0.8774, 0.7629],
        [0.7192, 0.4324, 0.2252],
        [0.9688, 0.7493, 0.7954]])


### dtype이 long이고 0으로 채워진 행렬 생성

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


### 데이터로부터 바로 tensor 생성

In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


### 존재하는 tensor를 이용하여 tensor 생성

In [7]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1168,  1.6068,  1.1137],
        [ 0.6838, -0.6493,  0.2314],
        [ 0.4702,  0.3059,  0.8980],
        [ 0.7499,  0.2762,  0.4500],
        [-0.7235,  0.8597,  0.6586]])


- 5*3의 1로 된 행렬을 만듦
- 위 행렬을 랜덤한 수로 채움

### 행렬 크기

In [8]:
print(x.size())

torch.Size([5, 3])


## 연산(Operations)

### 덧셈

In [12]:
y = torch.rand(5, 3)
print(x)
print(y)

tensor([[ 1.1168,  1.6068,  1.1137],
        [ 0.6838, -0.6493,  0.2314],
        [ 0.4702,  0.3059,  0.8980],
        [ 0.7499,  0.2762,  0.4500],
        [-0.7235,  0.8597,  0.6586]])
tensor([[0.2564, 0.6453, 0.4643],
        [0.1791, 0.7921, 0.4121],
        [0.1381, 0.6338, 0.5552],
        [0.2681, 0.9777, 0.7822],
        [0.2636, 0.4349, 0.1075]])


In [13]:
print(x + y)

tensor([[ 1.3731,  2.2520,  1.5780],
        [ 0.8628,  0.1428,  0.6435],
        [ 0.6082,  0.9397,  1.4532],
        [ 1.0180,  1.2539,  1.2321],
        [-0.4599,  1.2946,  0.7662]])


### 덧셈2

In [14]:
print(torch.add(x, y))

tensor([[ 1.3731,  2.2520,  1.5780],
        [ 0.8628,  0.1428,  0.6435],
        [ 0.6082,  0.9397,  1.4532],
        [ 1.0180,  1.2539,  1.2321],
        [-0.4599,  1.2946,  0.7662]])


### 덧셈3

In [15]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.3731,  2.2520,  1.5780],
        [ 0.8628,  0.1428,  0.6435],
        [ 0.6082,  0.9397,  1.4532],
        [ 1.0180,  1.2539,  1.2321],
        [-0.4599,  1.2946,  0.7662]])


- result 변수에 초기화되지 않은 5*3 행렬 입력
- torch.add 연산을 통해 x와 y를 더하고 그 결과값을 result에 저장

### 덧셈4

In [16]:
y.add_(x)
print(y)

tensor([[ 1.3731,  2.2520,  1.5780],
        [ 0.8628,  0.1428,  0.6435],
        [ 0.6082,  0.9397,  1.4532],
        [ 1.0180,  1.2539,  1.2321],
        [-0.4599,  1.2946,  0.7662]])


- y에 x더하기
- <span style="color:red">_접미사</span>를 통하여 바꿔치기 방식으로 tensor의 값 변경 가능
- ex) x.copy_(y), x.t_() 는 x를 변경함

### 인덱싱

In [18]:
print(x)
print(x[:, 1])

tensor([[ 1.1168,  1.6068,  1.1137],
        [ 0.6838, -0.6493,  0.2314],
        [ 0.4702,  0.3059,  0.8980],
        [ 0.7499,  0.2762,  0.4500],
        [-0.7235,  0.8597,  0.6586]])
tensor([ 1.6068, -0.6493,  0.3059,  0.2762,  0.8597])


### 크기 변경

In [20]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # 사이즈가 -1인 경우 다른 차원들을 사용하여 유우 가능
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [22]:
print(x)
print(y)
print(z)

tensor([[-0.9391,  0.6934,  0.5514, -2.0957],
        [ 0.2090, -0.7816,  0.0247, -1.1610],
        [-0.7879,  1.2660, -0.3784,  0.3314],
        [ 1.3093,  0.7702, -1.5320, -2.2203]])
tensor([-0.9391,  0.6934,  0.5514, -2.0957,  0.2090, -0.7816,  0.0247, -1.1610,
        -0.7879,  1.2660, -0.3784,  0.3314,  1.3093,  0.7702, -1.5320, -2.2203])
tensor([[-0.9391,  0.6934,  0.5514, -2.0957,  0.2090, -0.7816,  0.0247, -1.1610],
        [-0.7879,  1.2660, -0.3784,  0.3314,  1.3093,  0.7702, -1.5320, -2.2203]])


- 위 결과를 봤을 때 <span style="color:red">가로로 먼저 읽고</span> reshape를 진행하는 것을 볼 수 있음(MATLAB과는 반대)

### tensor 값 추출

In [23]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.6145])
0.6145038604736328


## NUMPY 변환 (BRIDGE)
- Torch Tensor와 Numpy 배열은 저장 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됨

### Torch Tensor -> Numpy

In [28]:
a = torch.ones(5)
print(a)
print(type(a))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>


In [29]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [30]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


- a와 b가 동시에 변하는 것을 볼 수 있음

### Numpy -> Torch Tensor

In [31]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


- 마찬가지로 a, b가 동시에 변하는 것을 볼 수 있음

## CUDA TENSORS

In [32]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))